version: '3'

services:
  web:
    image: docker.io/zecuria/docker-phoenix
    command: mix phx.server
    environment:
      - MIX_ENV=dev
      - PORT=4000
      - DATABASE_URL=ecto://postgres:postgres@postgres/dev_db
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    links:
      - postgres

  postgres:
    image: postgres:9.6.5
    ports:
      - "5432:5432"